cartpole_0:
  learning_rate: 0.01
  env_name: "CartPole-v0"
cartpole_1:
  learning_rate: 0.001
  env_name: "CartPole-v1"
car_discrete:
  learning_rate: !!float 1e-3
  n_epochs: 4
  batch_size: 64
  n_rollout_timesteps: 1024
  device: "cpu"
  env_name: "MountainCar-v0"
  obs_normalization: "simple"
  obs_shift: [0.5,0]
  obs_scale: [0.5,0.04]
car_continuous:
  learning_rate: !!float 1e-3
  n_epochs: 4
  batch_size: 64
  n_rollout_timesteps: 1024
  device: "cpu"
  env_name: "MountainCarContinuous-v0"
  obs_normalization: "simple"
  obs_shift: [0.5,0]
  obs_scale: [0.5,0.04]
lunar_continuous:
  env_name: "LunarLanderContinuous-v2"
  learning_rate: !!float 1e-4
  n_timesteps: !!float 1e6
  n_epochs: 4
  batch_size: 256
  n_rollout_timesteps: 256
  device: "cpu"