cartpole_0:
  learning_rate: 0.01
  env_name: "CartPole-v0"
cartpole_1:
  learning_rate: 0.001
  env_name: "CartPole-v1"
  n_timesteps: !!float 5e4
cartpole_1_e1:
  learning_rate: 0.001
  coeff_entropy: 0.01
  n_timesteps: !!float 1e5
  env_name: "CartPole-v1"
  device: "cpu"
cartpole_1_e2:
  learning_rate: 0.001
  coeff_entropy: 0.1
  n_timesteps: !!float 5e4
  env_name: "CartPole-v1"
cartpole_1_e3:
  learning_rate: 0.001
  coeff_entropy: 1
  n_timesteps: !!float 5e4
  env_name: "CartPole-v1"
cartpole_1_1:
  learning_rate: 1
  env_name: "CartPole-v1"

cartpole_exp:
  learning_rate: 0.01
  env_name: "CartPole-v0"
  device: "cpu"

car_e0:
  learning_rate: !!float 1e-3
  n_epochs: 4
  batch_size: 64
  n_rollout_timesteps: 1024
  device: "cpu"
  env_name: "MountainCar-v0"
  obs_normalization: "simple"
  obs_shift: [0.5,0]
  obs_scale: [0.5,0.04]
  # n_timesteps: !!float 5e4

car_e1:
  learning_rate: !!float 1e-3
  n_epochs: 4
  batch_size: 64
  n_rollout_timesteps: 1024
  device: "cpu"
  env_name: "MountainCar-v0"
  obs_normalization: "simple"
  obs_shift: [0.5,0]
  obs_scale: [0.5,0.04]
  coeff_entropy: 0.01
  # n_timesteps: !!float 5e4

car_e2:
  learning_rate: !!float 1e-3
  n_epochs: 4
  batch_size: 64
  n_rollout_timesteps: 1024
  device: "cpu"
  env_name: "MountainCar-v0"
  obs_normalization: "simple"
  obs_shift: [0.5,0]
  obs_scale: [0.5,0.04]
  coeff_entropy: 0.1
  # n_timesteps: !!float 5e4

car_e3:
  learning_rate: !!float 1e-3
  n_epochs: 4
  batch_size: 64
  n_rollout_timesteps: 1024
  device: "cpu"
  env_name: "MountainCar-v0"
  obs_normalization: "simple"
  obs_shift: [0.5,0]
  obs_scale: [0.5,0.04]
  coeff_entropy: 1
  # n_timesteps: !!float 5e4

car_e4:
  learning_rate: !!float 1e-3
  n_epochs: 4
  batch_size: 64
  n_rollout_timesteps: 1024
  device: "cpu"
  env_name: "MountainCar-v0"
  obs_normalization: "simple"
  obs_shift: [0.5,0]
  obs_scale: [0.5,0.04]
  coeff_entropy: 0.001
  # n_timesteps: !!float 5e4
ccar_no_norm:
  learning_rate: !!float 1e-3
  n_epochs: 4
  batch_size: 64
  n_rollout_timesteps: 1024
  device: "cpu"
  env_name: "MountainCarContinuous-v0"
  # obs_normalization: "simple"
  # obs_shift: [0.5,0]
  # obs_scale: [0.5,0.04]
  # coeff_entropy: 0.001


ccar_no_norm_e1:
  learning_rate: !!float 1e-3
  n_epochs: 4
  batch_size: 64
  n_rollout_timesteps: 1024
  device: "cpu"
  env_name: "MountainCarContinuous-v0"
  coeff_entropy: 0.001
ccar_no_norm_e2:
  learning_rate: !!float 1e-3
  n_epochs: 4
  batch_size: 64
  n_rollout_timesteps: 1024
  device: "cpu"
  env_name: "MountainCarContinuous-v0"
  coeff_entropy: 0.01
ccar_no_norm_e3:
  learning_rate: !!float 1e-3
  n_epochs: 4
  batch_size: 64
  n_rollout_timesteps: 1024
  device: "cpu"
  env_name: "MountainCarContinuous-v0"
  coeff_entropy: 0.1
ccar_no_norm_e4:
  learning_rate: !!float 1e-3
  n_epochs: 4
  batch_size: 64
  n_rollout_timesteps: 1024
  device: "cpu"
  env_name: "MountainCarContinuous-v0"
  coeff_entropy: 1

# python train.py -e ccar_no_norm & python train.py -e ccar_no_norm_e1 & python train.py -e ccar_no_norm_e2 & python train.py -e ccar_no_norm_e3 & python train.py -e ccar_no_norm_e4

car_discrete:
  learning_rate: !!float 1e-3
  n_epochs: 4
  batch_size: 64
  n_rollout_timesteps: 1024
  device: "cpu"
  env_name: "MountainCar-v0"
  obs_normalization: "simple"
  obs_shift: [0.5,0]
  obs_scale: [0.5,0.04]
car_continuous:
  learning_rate: !!float 1e-3
  n_epochs: 4
  batch_size: 64
  n_rollout_timesteps: 1024
  device: "cpu"
  env_name: "MountainCarContinuous-v0"
  obs_normalization: "simple"
  obs_shift: [0.5,0]
  obs_scale: [0.5,0.04]

lunar_d: # Lunar Lander Discrete
  env_name: "LunarLander-v2"
  learning_rate: !!float 1e-3
  n_timesteps: !!float 1e6
  n_epochs: 4
  batch_size: 256
  n_rollout_timesteps: 1024
  device: "cpu"
  coeff_entropy: 0.01

lunar_c:
  env_name: "LunarLanderContinuous-v2"
  learning_rate: !!float 1e-4
  n_timesteps: !!float 1e6
  n_epochs: 4
  batch_size: 256
  n_rollout_timesteps: 256
  device: "cpu"

cheetah:
  env_name: "HalfCheetahBulletEnv-v0"
  learning_rate: !!float 3e-4
  n_timesteps: !!float 20e6
  n_epochs: 10
  batch_size: 1024
  n_rollout_timesteps: 8096
  # device: "cuda"
  clip_range: 0.2
  max_grad_norm: 0.5
  # coeff_entropy: 0.01
  obs_normalization: "simple"
  obs_shift: !!seq [0.3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 0, 0, 1, 0, 0,0,0,-0.5,-0.5,-0.5,-0.5,-0.5,-0.5]
  obs_scale: !!seq [0.3, 1, 1, 2, 1, 1, 1, 4, 1, 3, 1, -1, 1, 5, 1, 5, 1, 1,1,1,1,1,1,1,1,1]
  #rew_normalization: "simple"
  #rew_shift: 3
  #rew_scale: 3
ch2:
  env_name: "HalfCheetahBulletEnv-v0"
  learning_rate: !!float 3e-5
  n_timesteps: !!float 20e6
  n_epochs: 10
  batch_size: 64
  n_rollout_timesteps: 2048
  device: "cpu"
  clip_range: 0.2
  max_grad_norm: 0.5
  net_size: 256
  # coeff_entropy: 0.01
  obs_normalization: "simple"
  obs_shift: !!seq [0.3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 0, 0, 1, 0, 0,0,0,-0.5,-0.5,-0.5,-0.5,-0.5,-0.5]
  obs_scale: !!seq [0.3, 1, 1, 2, 1, 1, 1, 4, 1, 3, 1, -1, 1, 5, 1, 5, 1, 1,1,1,1,1,1,1,1,1]
  #rew_normalization: "simple"
  #rew_shift: 3
  #rew_scale: 3

# Examples
# python train.py -e car_e0 & python train.py -e car_e1 & python train.py -e car_e2 & python train.py -e car_e3 & python train.py -e car_e4

biped:
  env_name: "BipedalWalker-v3"
  learning_rate: !!float 3e-4
  n_timesteps: !!float 20e6
  n_epochs: 10
  batch_size: 64
  n_rollout_timesteps: 2048
  device: "cpu"
  clip_range: 0.2
  max_grad_norm: 0.5"
  learning_rate: !!float 3e-5
  n_timesteps: !!float 20e6
  n_epochs: 10
  batch_size: 32
  n_rollout_timesteps: 2048
  device: "cpu"
  clip_range: 0.2
  max_grad_norm: 0.5
  net_size: 256
  obs_normalization: "simple"
  obs_shift: !!seq [0, 0, 0, 0, 0, 0, 0, 0, 0.5, 0, 0, 0, 0, 0.5, 0.5 ,0.5, 0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5]
  obs_scale: !!seq [1,1,1,1,1,1,1,1,0.5,1,1,1,1,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5]

biped_hard:
  env_name: "BipedalWalkerHardcore-v3"
  learning_rate: !!float 3e-4
  n_timesteps: !!float 20e6
  n_epochs: 10
  batch_size: 2048
  thresh_min_return: -2
  n_rollout_timesteps: 4098
  n_eval_episodes: 20
  device: "cpu"
  clip_range: 0.2
  max_grad_norm: 0.5"
  learning_rate: !!float 3e-5
  n_timesteps: !!float 20e6
  n_epochs: 10
  batch_size: 32
  n_rollout_timesteps: 2048
  device: "cpu"
  clip_range: 0.2
  max_grad_norm: 0.5
  net_size: 256
  obs_normalization: "simple"
  obs_shift: !!seq [0, 0, 0, 0, 0, 0, 0, 0, 0.5, 0, 0, 0, 0, 0.5, 0.5 ,0.5, 0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5]
  obs_scale: !!seq [1,1,1,1,1,1,1,1,0.5,1,1,1,1,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5]

acro:
  env_name: "Acrobot-v1"
  learning_rate: !!float 1e-4
  n_timesteps: !!float 1e6
  n_epochs: 4
  batch_size: 256
  n_rollout_timesteps: 1024
  device: "cpu"
  coeff_entropy: 0.01
  obs_normalization: "simple"
  obs_scale: [1,1,1,1,10,10]

acro_welford:
  env_name: "Acrobot-v1"
  learning_rate: !!float 1e-4
  n_timesteps: !!float 1e6
  n_epochs: 20
  batch_size: 256
  n_rollout_timesteps: 1024
  device: "cpu"
  coeff_entropy: 0.01
  obs_normalization: "welford"
  rew_normalization: "welford"
  # obs_scale: [1,1,1,1,10,10]

pendulum:
  env_name: "Pendulum-v0"
  learning_rate: !!float 1e-5
  n_timesteps: !!float 20e6
  n_epochs: 16
  batch_size: 1024
  n_rollout_timesteps: 2048
  device: "cpu"
  lda: 0.95
  gamma: 0.98
  net_size: 512
  action_scale: 2
  n_eval_episodes: 20
  # coeff_entropy: 0.01
bullet_pendulum:
  env_name: "InvertedPendulumSwingupBulletEnv-v0"
  learning_rate: !!float 1e-5
  n_timesteps: !!float 20e6
  n_epochs: 16
  batch_size: 1024
  n_rollout_timesteps: 2048
  device: "cpu"
  lda: 0.96
  gamma: 0.98
  net_size: 512
  n_eval_episodes: 20
  obs_normalization: "simple"
  obs_scale: [1, 5, 1, 1, 14]
car_racing:
  env_name: "CarRacing-v0"
  batch_size: 2048
  n_rollout_timesteps: 2048
  clip_range: 0.2
  max_grad_norm: 0.5
  lda: 0.96 #0.9
  gamma: 0.99
  thresh_min_return: -10
  learning_rate: !!float 3e-5
  n_timesteps: !!float 20e6
  wrappers: ["frame_stack"]
  policy: "cnn_car_racing"
  n_epochs: 8 #20
  # device: "cpu"
breakout_ram:
  env_name: "Breakout-ram-v0"
  learning_rate: !!float 3e-5
  wrappers: ["atari_ram_wrapper"]
  batch_size: 256
  n_rollout_timesteps: 2048
  clip_range: 0.2
  lda: 1
  net_size: 1024
  device: "cpu"
  gamma: 1
  learning_rate: !!float 3e-5
  n_timesteps: !!float 20e6
  n_epochs: 8
  coeff_entropy: 0.01

breakout:
  env_name: "Breakout-v0"
  learning_rate: !!float 3e-5
  wrappers: ["atari_wrapper"]
  batch_size: 512
  n_rollout_timesteps: 2048
  clip_range: 0.2
  adv_normalization: !!bool False
  lda: 1
  # net_size: 1024
  policy: "cnn_atari"
  # device: "cpu"
  gamma: 0.99
  learning_rate: !!float 3e-5
  n_timesteps: !!float 20e6
  n_epochs: 5
  coeff_entropy: 0.01
  n_eval_episodes: 10

seaquest:
  env_name: "Seaquest-v0"
  learning_rate: !!float 3e-5
  wrappers: ["atari_wrapper"]
  batch_size: 1024
  n_rollout_timesteps: 2048
  clip_range: 0.2
  lda: 1
  # net_size: 1024
  policy: "cnn_atari"
  # device: "cpu"
  gamma: 0.99
  learning_rate: !!float 3e-5
  n_timesteps: !!float 20e6
  n_epochs: 10
  coeff_entropy: 0.01

pong:
  env_name: "Pong-v0"
  learning_rate: !!float 3e-5
  wrappers: ["atari_wrapper"]
  batch_size: 256
  n_rollout_timesteps: 512
  clip_range: 0.2
  lda: 0.98
  # thresh_min_return: -0.5
  # net_size: 1024
  policy: "cnn_atari"
  adv_normalization: !!bool False
  # device: "cpu"
  gamma: 0.99
  # learning_rate: !!float 3e-5
  n_timesteps: !!float 20e6
  n_epochs: 10
  coeff_entropy: 0.01
car_welford:
  learning_rate: !!float 1e-3
  n_epochs: 4
  batch_size: 64
  n_rollout_timesteps: 1024
  device: "cpu"
  env_name: "MountainCar-v0"
  obs_normalization: "welford"
  lda: 0.98
  gamma: 0.99
  # obs_shift: [0.5,0]
  # obs_scale: [0.5,0.04]
  coeff_entropy: 0.01
ch_welford:
  env_name: "HalfCheetahBulletEnv-v0"
  learning_rate: !!float 3e-5
  n_timesteps: !!float 20e6
  n_epochs: 10
  batch_size: 64
  n_rollout_timesteps: 2048
  device: "cpu"
  clip_range: 0.2
  max_grad_norm: 0.5
  net_size: 256
  # coeff_entropy: 0.01
  obs_normalization: "welford"
  # obs_shift: !!seq [0.3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 0, 0, 1, 0, 0,0,0,-0.5,-0.5,-0.5,-0.5,-0.5,-0.5]
  # obs_scale: !!seq [0.3, 1, 1, 2, 1, 1, 1, 4, 1, 3, 1, -1, 1, 5, 1, 5, 1, 1,1,1,1,1,1,1,1,1]
ant_welford:
  env_name: "AntBulletEnv-v0"
  learning_rate: !!float 3e-5
  n_timesteps: !!float 20e6
  n_epochs: 10
  batch_size: 64
  n_rollout_timesteps: 2048
  device: "cpu"
  clip_range: 0.2
  max_grad_norm: 0.5
  net_size: 256
  # coeff_entropy: 0.01
  obs_normalization: "welford"
hopper_welford:
  env_name: "HopperBulletEnv-v0"
  learning_rate: !!float 3e-5
  n_timesteps: !!float 20e6
  n_epochs: 10
  batch_size: 1024
  n_rollout_timesteps: 2048
  device: "cpu"
  clip_range: 0.2
  max_grad_norm: 0.5
  net_size: 256
  # coeff_entropy: 0.01
  obs_normalization: "welford"
walker_welford:
  env_name: "Walker2DBulletEnv-v0"
  learning_rate: !!float 3e-5
  n_timesteps: !!float 20e6
  n_epochs: 10
  batch_size: 64
  n_rollout_timesteps: 2048
  device: "cpu"
  clip_range: 0.2
  max_grad_norm: 0.5
  net_size: 256
  # coeff_entropy: 0.01
  obs_normalization: "welford"
inverted_pendulum_welford:
  env_name: "InvertedPendulumSwingupBulletEnv-v0"
  learning_rate: !!float 3e-5
  n_timesteps: !!float 10e6
  n_epochs: 10
  batch_size: 64
  n_rollout_timesteps: 2048
  device: "cpu"
  clip_range: 0.2
  max_grad_norm: 0.5
  net_size: 256
  # coeff_entropy: 0.01
  obs_normalization: "welford"
car_d_rew:
  env_name: "MountainCar-v0"
  learning_rate: !!float 3e-5
  n_timesteps: !!float 1e6
  n_epochs: 4
  batch_size: 64
  n_rollout_timesteps: 512
  device: "cpu"
  clip_range: 0.2
  # max_grad_norm: 0.5
  # net_size: 256
  # coeff_entropy: 0.01
  obs_normalization: "welford"
  rew_normalization: "welford"
biped_hard_welford:
  env_name: "BipedalWalkerHardcore-v3"
  n_eval_episodes: 20
  device: "cpu"
  clip_range: 0.2
  max_grad_norm: 0.5"
  learning_rate: !!float 3e-5
  n_timesteps: !!float 20e6
  n_epochs: 10
  batch_size: 128
  n_rollout_timesteps: 2048
  device: "cpu"
  clip_range: 0.2
  max_grad_norm: 0.5
  net_size: 512
  lda: 0.96
  gamma: 0.98
  coeff_entropy: 0.01
  obs_normalization: "welford"
  rew_normalization: "welford"
  # obs_shift: !!seq [0, 0, 0, 0, 0, 0, 0, 0, 0.5, 0, 0, 0, 0, 0.5, 0.5 ,0.5, 0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5]
  # obs_scale: !!seq [1,1,1,1,1,1,1,1,0.5,1,1,1,1,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5]
biped_hard_ignore_fail:
  env_name: "BipedalWalkerHardcore-v3"
  n_eval_episodes: 20
  device: "cpu"
  clip_range: 0.2
  max_grad_norm: 0.5"
  learning_rate: !!float 3e-5
  n_timesteps: !!float 20e6
  n_epochs: 10
  batch_size: 128
  n_rollout_timesteps: 2048
  device: "cpu"
  clip_range: 0.2
  max_grad_norm: 0.5
  net_size: 512
  lda: 0.96
  gamma: 0.98
  coeff_entropy: 0.01
  obs_normalization: "welford"
  rew_normalization: "welford"
breakout_2:
  env_name: "Breakout-v0"
  learning_rate: !!float 3e-4
  wrappers: ["breakout_blind_wrapper"]
  batch_size: 512
  n_rollout_timesteps: 2048
  clip_range: 0.2
  adv_normalization: !!bool False
  lda: 1
  # net_size: 1024
  policy: "cnn_atari"
  # device: "cpu"
  gamma: 0.999
  learning_rate: !!float 3e-4
  n_timesteps: !!float 20e6
  n_epochs: 5
  coeff_entropy: 0.01
  n_eval_episodes: 10
humanoid_welford:
  env_name: "HumanoidBulletEnv-v0"
  learning_rate: !!float 3e-5
  n_timesteps: !!float 20e6
  n_epochs: 10
  batch_size: 64
  n_rollout_timesteps: 2048
  device: "cpu"
  clip_range: 0.2
  max_grad_norm: 0.5
  net_size: 512
  obs_normalization: "welford"
test_save_and_reload:
  learning_rate: 0.001
  env_name: "CartPole-v0"

bh_high:
  env_name: "BipedalWalkerHardcore-v3"
  n_eval_episodes: 20
  clip_range: 0.2
  max_grad_norm: 0.5"
  learning_rate: !!float 3e-4
  n_timesteps: !!float 20e6
  n_epochs: 10
  batch_size: 4096
  n_rollout_timesteps: 4096
  max_grad_norm: 0.5
  net_size: 1024
  lda: 0.96
  gamma: 0.98
  device: "cpu"
  coeff_entropy: 0.01
  obs_normalization: "welford"
  rew_normalization: "welford"
car_e11:
  learning_rate: !!float 1e-3
  n_epochs: 4
  batch_size: 1024
  n_rollout_timesteps: 1024
  n_eval_episodes: 20
  device: "cpu"
  env_name: "MountainCar-v0"
  obs_normalization: "simple"
  obs_shift: [0.5,0]
  obs_scale: [0.5,0.04]
  coeff_entropy: 0.01
car_e11_welford:
  learning_rate: !!float 1e-3
  n_epochs: 4
  batch_size: 1024
  n_rollout_timesteps: 1024
  n_eval_episodes: 20
  device: "cpu"
  env_name: "MountainCar-v0"
  obs_normalization: "welford"
  # obs_shift: [0.5,0]
  # obs_scale: [0.5,0.04]
  coeff_entropy: 0.01

car_racing_2:
  env_name: "CarRacing-v0"
  batch_size: 1024
  n_rollout_timesteps: 2048
  clip_range: 0.2
  max_grad_norm: 0.5
  lda: 0.96 #0.9
  gamma: 0.99
  # thresh_min_return: -10
  learning_rate: !!float 1e-4
  n_timesteps: !!float 20e6
  wrappers: ["frame_stack"]
  policy: "cnn_car_racing"
  n_epochs: 10
  n_eval_episodes: 10

bh_high_2:
  env_name: "BipedalWalkerHardcore-v3"
  n_eval_episodes: 20
  clip_range: 0.2
  max_grad_norm: 0.5"
  learning_rate: !!float 3e-4
  n_timesteps: !!float 20e6
  n_epochs: 10
  batch_size: 256
  n_rollout_timesteps: 1024
  max_grad_norm: 0.5
  net_size: 1024
  lda: 0.95
  gamma: 0.99
  device: "cpu"
  coeff_entropy: 0.01
  obs_normalization: "welford"
  # rew_normalization: "welford"
multi:
  env_name: "CartPole-v0"
  n_envs: 100
  n_rollout_timesteps: 1000
  batch_size: 1000
  device: "cpu"
pendulum_multi:
  env_name: "Pendulum-v0"
  learning_rate: !!float 1e-4
  n_epochs: 20
  n_envs: 10
  n_rollout_timesteps: 256
  batch_size: 1024
  device: "cpu"

lunar_multi:
  env_name: "LunarLanderContinuous-v2"
  learning_rate: !!float 1e-4
  n_envs: 10
  n_rollout_timesteps: 256
  batch_size: 1024
  device: "cpu"
  